export const INCREMENT = 'INCREMENT';
export const DRAW_MAP = 'DRAW_MAP';
export const CELL_NUMBER_MAP = 'DRAW_CELL_NUMBER_MAP';
export const CREATE_DATA_MAP = 'CREATE_DATA_MAP';
export const SOMADHAN_CHHOKK = 'SOMADHAN_CHHOK';
export const CURRENT_LOCATION_PATH = 'CURRENT_LOCATION_PATH';
export const CREATE_USER_PROFILE = 'CREATE_USER_PROFILE';